name: needsandif
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.output1 != 'hello' }} && (github.event_name == 'push' || github.event_name == 'pull_request')
    steps:
      - run: echo "${{needs.job1.outputs.output1}}"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.output1 != 'hello' }} 
    steps:
      - run: echo "I won't run"
     
