name: requiredjobskip
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Always fail job
        run: |
          echo "I failed :("
          exit 0
  test-status-check:
    name: test-status-check
    runs-on: ubuntu-latest
    if: always()
    needs: test-fail-job
    steps:
      - name: Fail step
        if: ${{ needs.test-fail-job.result != 'success' }}
        run: |
          echo "${{ toJSON(needs.test-fail-job) }}"
          exit 1
      - name: Additional step
        run: echo "I will run only if the independent job completed with 'success'"
