name: requiredjobskip
on:
  workflow_dispatch:
jobs:
  test-fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Always fail job
        run: |
          echo "I failed :("
          exit 1
  test-status-check:
    name: test-status-check
    runs-on: ubuntu-latest
    if: always()
    needs: test-fail-job
    steps:
      - name: Test status of needs job Failure
        run: |
          echo "this should never run"
          exit 1
