name: skip
on: [push,workflow_dispatch]

jobs:
  always-skipped:
    runs-on: ubuntu-latest
    if: false
    steps:
      - shell: bash
        run: echo "This job will always be skipped"
  always-success:
    runs-on: ubuntu-latest
    if: true
    steps:
      - shell: bash
        run: echo "This job will always succeed"

  runs-upon-success:
    runs-on: ubuntu-latest
    needs:
      - always-skipped
      - always-success
#     if: "!(failure() || cancelled())"
    if: "some random string"
    steps:
      - shell: bash
        run: echo "What happens here"
